theme="polymer"

baseurl = "https://blog.abourget.net"
languageCode = "en-us"
title = "geek joy"

MetaDataFormat = "toml"
paginate = 10 # optional
# disqusShortname = "Alexandre Bourget" # optional
copyright = "Â© 2015 Copyright Alexandre Bourget"

[params]
  author = "Alexandre Bourget"
#  photo = "images/photo.jpg" # optional
  profile = "images/profile.jpg" # optional
  cover = "images/cover.jpg" # optional
  twitter = "bourgetalexndre" # optional
  github = "abourget" # optional
#  facebook = "Your facebook Name" # optional
#  gplus = "Your Google+ Name" # optional
  linkedin = "alexandrebourget" # optional
#  googleAnalyticsUserID = "Your Analytics User Id" # optional

[permalinks]
  post = "/:year/:month/:day/:filename/"
