---
theme: "polymer"

baseurl: "https://blog.abourget.net"

paginate: 10 # optional
disqusShortname: "blogabourget" # optional

DefaultContentLang: en

Multilingual:
  en:
    weight: 1

    title: "geek joy"

    languageCode: "en-US"
    copyright: "(ɔ) 2015 Copyleft. Alexandre Bourget."

    params:
      author: "Alexandre Bourget"
      profile: "images/profile.jpg" # optional
      cover: "images/cover-bw.jpg" # optional
      twitter: "bourgetalexndre" # optional
      github: "abourget" # optional
      linkedin: "alexandrebourget" # optional
      googleAnalyticsUserID: "UA-12745853-1"

  fr:
    weight: 2

    title: "la joie geek"

    languageCode: "fr-CA"
    copyright: "(ɔ) 2015 Other override here.."

    params:
      author: "Alexandre Bourget"
      profile: "images/profile.jpg" # optional
      cover: "images/cover-bw.jpg" # optional
      twitter: "bourgetalexndre" # optional
      github: "abourget" # optional
      linkedin: "alexandrebourget" # optional
      googleAnalyticsUserID: "UA-12745853-1"

permalinks:
  post: "/:year/:month/:day/:filename/"

MetaDataFormat: "yaml"
